-- Contact / quote inquiry form storage
-- Run in Supabase Dashboard > SQL Editor

create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  source text not null default 'quote',
  created_at timestamptz not null default now()
);

alter table public.contact_inquiries enable row level security;

drop policy if exists "Public can submit contact inquiries" on public.contact_inquiries;
create policy "Public can submit contact inquiries"
on public.contact_inquiries for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read contact inquiries" on public.contact_inquiries;
create policy "Admins can read contact inquiries"
on public.contact_inquiries for select
to authenticated
using (public.is_admin());

create index if not exists contact_inquiries_created_at_idx
  on public.contact_inquiries (created_at desc);
